// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamManagementService.Data;

#nullable disable

namespace TeamManagementService.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TeamManagementService.Models.BusinessUnit", b =>
                {
                    b.Property<int>("BU_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BU_Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("BU_Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BU_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BU_Type")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("BU_Id");

                    b.ToTable("BusinessUnits");
                });

            modelBuilder.Entity("TeamManagementService.Models.BusinessUnitCategory", b =>
                {
                    b.Property<int>("BUC_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BUC_Id"), 1L, 1);

                    b.Property<int>("BU_Id")
                        .HasColumnType("int");

                    b.Property<string>("ZurichLineOfBusiness")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("BUC_Id");

                    b.HasIndex("BU_Id");

                    b.ToTable("BusinessUnitCategories");
                });

            modelBuilder.Entity("TeamManagementService.Models.BusinessUnitMember", b =>
                {
                    b.Property<int>("BUM_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BUM_Id"), 1L, 1);

                    b.Property<int>("BU_Id")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeLoginId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsManager")
                        .HasColumnType("bit");

                    b.HasKey("BUM_Id");

                    b.HasIndex("BU_Id");

                    b.ToTable("BusinessUnitMembers");
                });

            modelBuilder.Entity("TeamManagementService.Models.Employee", b =>
                {
                    b.Property<string>("Emp_LoginID")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("BU_Id")
                        .HasColumnType("int");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("Emp_LoginID");

                    b.HasIndex("BU_Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("TeamManagementService.Models.BusinessUnitCategory", b =>
                {
                    b.HasOne("TeamManagementService.Models.BusinessUnit", null)
                        .WithMany()
                        .HasForeignKey("BU_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeamManagementService.Models.BusinessUnitMember", b =>
                {
                    b.HasOne("TeamManagementService.Models.BusinessUnit", null)
                        .WithMany()
                        .HasForeignKey("BU_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeamManagementService.Models.Employee", b =>
                {
                    b.HasOne("TeamManagementService.Models.BusinessUnit", null)
                        .WithMany()
                        .HasForeignKey("BU_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
